<?php

namespace Database\Seeders;

use App\Models\DataVK;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class DataVKSeeder extends Seeder
{
    public function run(): void
    {
        $dataVK = [
            // ==================== JANUARI 2025 ====================
            ['tanggal' => '2025-01-01', 'nama_pasien' => 'NY. DESTRIYANI', 'no_rm' => '068874', 'status_rawat' => 'BPJS / 1', 'diagnosa' => 'G2P1A0 HAMIL 38-39 MGG DENGAN PEB', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP.OG', 'asisten_tindakan' => 'Grenvy - ASTRID - GUSTI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-01-03', 'nama_pasien' => 'NY. NURAINI', 'no_rm' => '062670', 'status_rawat' => 'BPJS / 1', 'diagnosa' => 'G1P0A0 HAMIL 7 MGG DENGAN DEATH CONCEPTION', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. YULIUS, SP.OG', 'dokter_anestesi' => 'DR. WIMA, SP. AN', 'asisten_tindakan' => 'Grenvy- GUSTI', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-01-04', 'nama_pasien' => 'NY. YULI YULIANTI', 'no_rm' => '068974', 'status_rawat' => 'BPJS / 3', 'diagnosa' => 'G3P1A0 HAMIL 7 MGG DENGAN AB. INKOMPLIT', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. YULIUS, SP.OG', 'penata_anestesi' => 'MEGA', 'asisten_tindakan' => 'Grenvy - JESSICA', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-01-04', 'nama_pasien' => 'NY. DEDE MULYANIH', 'no_rm' => '053972', 'status_rawat' => 'BPJS / 1', 'diagnosa' => 'G3P2A0 HAMIL 35-36 MGG DGN KPD + INPARTU KALA I FASE AKTIF', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP.OG', 'dokter_anak' => 'DR. MARIA', 'asisten_tindakan' => 'Grenvy - LIKA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-01-10', 'nama_pasien' => 'NY. KHOIRUNNISA', 'no_rm' => '068285', 'status_rawat' => 'BPJS / 3', 'diagnosa' => 'G4P3A0 HAMIL 37 MGG DGN INPARTU KALA 1 FASE LATEN', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP.OG', 'asisten_tindakan' => 'Grenvy - GUSTI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-01-12', 'nama_pasien' => 'NY. SRI HANDAYANI', 'no_rm' => '069222', 'status_rawat' => 'BPJS / 3', 'diagnosa' => 'G2P1A0 HAMIL 6 MGG DGN ABORTUS INKOMPLIT', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. JUMADI, SP.OG', 'dokter_anestesi' => 'DR. GHAFFAR, SP.AN', 'asisten_tindakan' => 'Grenvy - DILA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-01-13', 'nama_pasien' => 'NY. WIWIK ANGGRAYNI', 'no_rm' => '069170', 'status_rawat' => 'BPJS / 3', 'diagnosa' => 'G6P3A0 HAMIL 10 MGG DGN MISSED ABORTION', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. YULIANA, SP.OG', 'dokter_anestesi' => 'DR. WIMA, SP. AN', 'asisten_tindakan' => 'Grenvy - NINING', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-01-20', 'nama_pasien' => 'NY. ANI SURYANI', 'no_rm' => '069505', 'status_rawat' => 'BPJS / 2', 'diagnosa' => 'G4P2A1 HAMIL 9 MGG DGN BLIGHTED OVUM', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. YULIANA, SP.OG', 'dokter_anestesi' => 'DR. WIMA, SP. AN', 'asisten_tindakan' => 'Grenvy - YOHANA', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-01-22', 'nama_pasien' => 'NY. NURMALA', 'no_rm' => '069554', 'status_rawat' => 'BPJS / 1', 'diagnosa' => 'G2P1A0 HAMIL 12 MGG DGN AB. INKOMPLIT', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. YULIANA, SP.OG', 'dokter_anestesi' => 'DR. GHAFFAR, SP.AN', 'asisten_tindakan' => 'Grenvy - YOHANA', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-01-24', 'nama_pasien' => 'NY. SITI NURHASANAH', 'no_rm' => '069618', 'status_rawat' => 'BPJS / 3', 'diagnosa' => 'G4P0A3 HAMIL 6 MGG DGN BLIGHTED OVUM', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. JUMADI, SP.OG', 'dokter_anestesi' => 'DR. WIMA, SP. AN', 'asisten_tindakan' => 'Grenvy - YOHANA', 'penolong_persalinan' => 'DOKTER'],
            
            // ==================== FEBRUARI 2025 ====================
            ['tanggal' => '2025-02-06', 'nama_pasien' => 'NY. BAETI INAYAH', 'no_rm' => '066063', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G3P2A0 HAMIL 37 MGG DENGAN KPD + SUSP PEB', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'dokter_anak' => 'DR. MARIA', 'asisten_tindakan' => 'Grenvy - MEI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-02-12', 'nama_pasien' => 'NY. SITI TOIROH', 'no_rm' => '070362', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G1P0A0 HAMIL 42 MGG (SEROTINUS) DGN INPARTU KALA I FASE AKTIF + LASERASI GRADE II', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'dokter_anak' => 'DR. MARIA', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-02-18', 'nama_pasien' => 'NY. NOVITA NUROH', 'no_rm' => '070572', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G5P4A0 HAMIL 40 MGG DENGAN INPARU KALA I FASE AKTIF + KPD', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIUS, SP. OG', 'dokter_anak' => 'DR. SYAQOFI', 'asisten_tindakan' => 'Grenvy - MEI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-02-21', 'nama_pasien' => 'NY. YULIANA', 'no_rm' => '070622', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'PUD', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'dokter_anestesi' => 'DR. WIMA, SP.AN', 'asisten_tindakan' => 'Grenvy - JESSICA', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-02-26', 'nama_pasien' => 'NY. TANIA PUTRI', 'no_rm' => '068956', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G1P0A0 HAMIL 38MGG INPARTU KALA I FASE AKTIF DENGAN CONDILOMA + LASERASI GRADE II', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'Grenvy - YOHANA', 'penolong_persalinan' => 'BIDAN'],
            
            // ==================== MARET 2025 ====================
            ['tanggal' => '2025-03-04', 'nama_pasien' => 'NY. JUNAINAH', 'no_rm' => '026514', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G3P2A0 HAMIL 38 MGG', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'Grenvy - FENI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-03-05', 'nama_pasien' => 'NY. SUCI RAMADANI', 'no_rm' => '071115', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G2P1A0 HAMIL 13 MGG DGN MISSED ABORTION', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'dokter_anestesi' => 'DR. GHAFFAR, SP. AN', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-03-20', 'nama_pasien' => 'NY. INDRIYA NUR AINI', 'no_rm' => '049566', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G2P1A0 HAMIL 40-41 MGG DGN INPARTU KALA I FASE AKTIF + SEROTINUS + LASERASI GRADE II', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIUS, SP. OG', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-03-23', 'nama_pasien' => 'NY. YATI', 'no_rm' => '061732', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G3P2A0 HAMIL 38 - 39 MGG DGN KPD', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'dokter_anak' => 'DR. IVORY', 'asisten_tindakan' => 'Grenvy - FENI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-03-24', 'nama_pasien' => 'NY. MALIYAH', 'no_rm' => '071429', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G4P3A0 HAMIL 40-41 MGG DGN SEROTINUS', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'Grenvy - ASTRID', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-03-25', 'nama_pasien' => 'NY. ADITYARA', 'no_rm' => '', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G2P1A0 HAMIL 37-38 MGG DGN KALA I FASE LATEN + RIWAYAT HIPERTIROID', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'dokter_anak' => 'DR. ANGGI', 'asisten_tindakan' => 'Grenvy - DILA', 'penolong_persalinan' => 'BIDAN'],
            
            // ==================== APRIL 2025 ====================
            ['tanggal' => '2025-04-10', 'nama_pasien' => 'NY. RENI', 'no_rm' => '072200', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G4P2A1 HAMIL 8 MGG DGN BLIGHTED OVUM', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'dokter_anestesi' => 'DR. GHAFFAR, SP. AN', 'asisten_tindakan' => 'Grenvy - FENI', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-04-10', 'nama_pasien' => 'NY. YUNITA', 'no_rm' => '072212', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G4P2A1 HAMIL 8 MGG DGN BLIGHTED OVUM', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'dokter_anestesi' => 'DR. GHAFFAR, SP. AN', 'asisten_tindakan' => 'Grenvy - FENI', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-04-11', 'nama_pasien' => 'NY. SAHILA RAMADHANI', 'no_rm' => '072282', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G1P0A0 HAMIL 37 MGG DGN INPARTU KALA I FASE AKTIF + KPD 6 JAM + LASERASI GRADE II', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIUS, SP. OG', 'asisten_tindakan' => 'Grenvy - CAHAYA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-04-16', 'nama_pasien' => 'NY. EKA SURYANIH', 'no_rm' => '071911', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G3P2A0 HAMIL 41 MGG DGN INPARTU KALA I FASE AKTIF + SEROTINUS + LASERASI GRADE II + LTP 1x', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'dokter_anak' => 'DR. SYAQOFI', 'asisten_tindakan' => 'Grenvy - YOHANA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-04-25', 'nama_pasien' => 'ENTIN', 'no_rm' => '072516', 'status_rawat' => 'BPJS / I', 'diagnosa' => 'POST MENOPOUSE BLIDIN EC POLIF+AFF IUD', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'dokter_anestesi' => 'DR. ARIA, SP. AN', 'penata_anestesi' => 'MEGA', 'asisten_tindakan' => 'Grenvy - YOHANA', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-04-25', 'nama_pasien' => 'ENTIN', 'no_rm' => '072516', 'status_rawat' => 'BPJS / I', 'diagnosa' => 'POST MENOPOUSE BLIDIN EC POLIF+AFF IUD', 'tindakan' => 'KURET', 'pemeriksaan_pa' => 'YA', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'dokter_anestesi' => 'DR. ARIA, SP. AN', 'penata_anestesi' => 'MEGA', 'asisten_tindakan' => 'Grenvy - YOHANA', 'penolong_persalinan' => 'DOKTER'],
            
            // ==================== MEI 2025 ====================
            ['tanggal' => '2025-05-01', 'nama_pasien' => 'NY, EPI YULIANA', 'no_rm' => '072904', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G3P2A0 HAMIL 8 MGG DGN ABORTUS INKOMPLIT', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'penata_anestesi' => 'MEGA', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-05-02', 'nama_pasien' => 'NY. QOTRUNNADA', 'no_rm' => '059092', 'status_rawat' => 'UMUM / III', 'diagnosa' => 'G1P0A0 HAMIL 38 MGG DGN INPARTU KALA I FASE AKTIF', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'dokter_anak' => 'DR. SELLY', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-05-03', 'nama_pasien' => 'NY. FITRIYAH', 'no_rm' => '043795', 'status_rawat' => 'BPJS / I', 'diagnosa' => 'G3P1A1 HAMIL 38 MGG DGN PEB + LASERASI GRADE III', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-05-20', 'nama_pasien' => 'NY. AULIA NOVA', 'no_rm' => '073477', 'status_rawat' => 'UMUM / I', 'diagnosa' => 'G1P0A0 HAMIL 21 MGG DGN IUFD + LASERASI GRADE II', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-05-23', 'nama_pasien' => 'NY. FITRIYANTI', 'no_rm' => '73545', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'PUA', 'tindakan' => 'KURET', 'pemeriksaan_pa' => 'YA', 'nama_dokter' => 'DR. STEPHANUS, SP.OG', 'dokter_anestesi' => 'DR. ARIA, SP. AN', 'penata_anestesi' => 'YUNI', 'asisten_tindakan' => 'Grenvy- YOHANA', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-05-24', 'nama_pasien' => 'NY. DEWI WULANDARI', 'no_rm' => '073633', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G4P3A0 HAMIL 38 MGG', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'BIDAN'],
            
            // ==================== JUNI 2025 ====================
            ['tanggal' => '2025-06-03', 'nama_pasien' => 'NY. DINI FITRIANI', 'no_rm' => '042252', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G6P4A1 HAMIL 12 MGG DGN SUSP. ABORTUS INKOMPLIT', 'tindakan' => 'KURET', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'dokter_anestesi' => 'DR. GHAFFAR, SP. AN', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-06-08', 'nama_pasien' => 'NY. LITA', 'no_rm' => '073949', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G5P4A1 HAMIL 38 - 39 MGG', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-06-10', 'nama_pasien' => 'NY. MAEMUNAH', 'no_rm' => '073868', 'status_rawat' => 'BPJS / I', 'diagnosa' => 'P3A0 DENGAN CONDILOMA AKUMINATA + IUD INSITU', 'tindakan' => 'KAUTERISASI', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'penata_anestesi' => 'MEGA', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-06-15', 'nama_pasien' => 'NY. SITI MARIAM', 'no_rm' => '071727', 'status_rawat' => 'BPJS / I', 'diagnosa' => 'G2P1A0 HAMIL 37 - 38 MGG DGN KPD 6 JAM + INPARTU KALA I FASE LATEN + HECTING GRADE II', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-06-26', 'nama_pasien' => 'NY. HILDA', 'no_rm' => '060867', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G2P1A0 HAMIL 40-41 MGG DGN SEROTINUS + INPARTU KALA I FASE AKTIF + LASERASI GRADE II', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'BIDAN'],
            
            // ==================== JULI 2025 ====================
            ['tanggal' => '2025-07-07', 'nama_pasien' => 'NY VIDIANA', 'no_rm' => '70980', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G1P0AO H 39 MGG A/I OLIGOHIDRAMNION', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR STEFANUS SPOG', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-07-07', 'nama_pasien' => 'NY STEFI', 'no_rm' => '72449', 'status_rawat' => 'BPJS III', 'diagnosa' => 'G2P1A0 H42 W DGN KPD, SEROTINUS, LASERASI GRADE 3', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP.OG', 'asisten_tindakan' => 'Grenvy, BD YOHANA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-07-11', 'nama_pasien' => 'NY VIARANI', 'no_rm' => '71540', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G1P0A0 H 31 MGG A/I KPD', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR JUMADI SPOG', 'asisten_tindakan' => 'Grenvy, BD JESICA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-07-11', 'nama_pasien' => 'NY VARIDA', 'no_rm' => '74911', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G1P0A0 H 37 MGG A/I KPD', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR STEFANUS SPOG', 'asisten_tindakan' => 'Grenvy, BD FENI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-07-11', 'nama_pasien' => 'NY NINDA', 'no_rm' => '73892', 'status_rawat' => 'BPJS/I', 'diagnosa' => 'G1P0A0 H 39 MGG DENGAN KPD+MYOPIA', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR JUMADI SPOG', 'asisten_tindakan' => 'Grenvy, BD JESICA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-07-22', 'nama_pasien' => 'NY. TRIMALA', 'no_rm' => '73900', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G1P0A0 HAMIL 39-40 MGG DGN INPARTU KALA I FASE AKRIF', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'asisten_tindakan' => 'Grenvy , BD. NINING', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-07-26', 'nama_pasien' => 'NY. MAENIROH', 'no_rm' => '74981', 'status_rawat' => 'BPJS/I', 'diagnosa' => 'G2P1A0 HAMIL 9 MGG DGN ABORTUS INKOMPLIT + PRIMISEKUNDI', 'tindakan' => 'KURETASE', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'dokter_anestesi' => 'DR. ARIA, SP. AN', 'asisten_tindakan' => 'Grenvy', 'penolong_persalinan' => 'DOKTER'],
            
            // ==================== AGUSTUS 2025 ====================
            ['tanggal' => '2025-08-05', 'nama_pasien' => 'NY. JULIA SHINTA', 'no_rm' => '21395', 'status_rawat' => 'BPJS/I', 'diagnosa' => 'G4P3A0 HAMIL 39-40 MGG DGN INPARTU KALA I FASE AKTIF + RIW. ANOMALI KONGINETAL + ANEMIA RINGAN + LASERASI GRADE II', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'asisten_tindakan' => 'BD Grenvy , BD. NINING', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-08-08', 'nama_pasien' => 'NY. DWI LUVI', 'no_rm' => '50840', 'status_rawat' => 'BPJS/I', 'diagnosa' => 'G1P0A0 HAMIL 34-35 MGG DGN KPD', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'BD. Grenvy, BD. NINING', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-08-12', 'nama_pasien' => 'NY. AUDI ZARA', 'no_rm' => '74778', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G1P0A0 HAMIL 7-8 MGG DGN ABORTUS INKOMPLIT', 'tindakan' => 'KURETASE', 'pemeriksaan_pa' => 'YA', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'penata_anestesi' => 'MEGA', 'asisten_tindakan' => 'BD. Grenvy, BD. NINING', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-08-13', 'nama_pasien' => 'NY. LULU', 'no_rm' => '75420', 'status_rawat' => 'BPJS/II naik kelas 1', 'diagnosa' => 'G1P0A0 HAMIL 40-41 MGG DGN KPD + INERSIA UTERI', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'asisten_tindakan' => 'BD Grenvy', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-08-14', 'nama_pasien' => 'NY. SARI WIDYANINGSIH', 'no_rm' => '75952', 'status_rawat' => 'UHC', 'diagnosa' => 'G3P2A0 HAMIL 36-37 MGG DGN INERSIA UTERI', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. YANTI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-08-15', 'nama_pasien' => 'NY. MUTHIA PUTRI', 'no_rm' => '74480', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G5P3A1 HAMIL 41 MGG DGN KALA 1 FASE LATEN + BSC 1', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. ALYA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-08-16', 'nama_pasien' => 'NY. KHARIROH', 'no_rm' => '39171', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G7P6A0 HAMIL 39-40 MGG DGN LTP 2X', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. FENI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-08-18', 'nama_pasien' => 'NY. IKA KARTIKA', 'no_rm' => '76025', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G2P1A0 HAMIL 41-42 MGG DGN SEROTINUS + INPARTU KALA I FASE AKTIF + RIW. PERDARAHAN POST PARTUM + HECTING GRADE II', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. OKTA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-08-19', 'nama_pasien' => 'NY. SITI AMINAH', 'no_rm' => '76043', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G3P2A0 HAMIL 41-42 MGG DGN SEROTINUS + HRP + PRIMISEKUNDI + OLIGOHIDRAMNION + MANUAL PLASENTA + LASERASI GRADE 3', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. YOHANA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-08-19', 'nama_pasien' => 'NY. FEBIOLA', 'no_rm' => '76074', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G4P2A1 HAMIL 37-38 MGG DGN INPARTU KALA 1 FASE AKTIF + LASERASI GRADE II', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'BD Grenvy , BD. ADIS', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-08-22', 'nama_pasien' => 'NY. DINI', 'no_rm' => '76174', 'status_rawat' => 'BPJS/II', 'diagnosa' => 'G2P1A0 HAMIL 8 MGG DGN ABORTUS INKOMPLIT', 'tindakan' => 'KURETASE', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'dokter_anestesi' => 'DR. ALFIANDY, SP. AN', 'penata_anestesi' => 'YUNI', 'asisten_tindakan' => 'BD Grenvy, BD. NINING', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-08-23', 'nama_pasien' => 'NY. SINDI PUJI RAHAYU', 'no_rm' => '76179', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G1P0A0 HAMIL 8 MGG DGN BLIGHTED OVUM', 'tindakan' => 'KURETASE', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'dokter_anestesi' => 'DR. ALFIANDY, SP. AN', 'penata_anestesi' => 'MEGA', 'asisten_tindakan' => 'BD Grenvy', 'penolong_persalinan' => 'DOKTER'],
            
            // ==================== SEPTEMBER 2025 ====================
            ['tanggal' => '2025-09-01', 'nama_pasien' => 'TUTIK', 'no_rm' => '071320', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G2P1AO H 41-42 MGG DENGAN SEROTINUS+KPD', 'tindakan' => 'PARTUS SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD MEI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-09-10', 'nama_pasien' => 'SITI FAUZIAH', 'no_rm' => '004534', 'status_rawat' => 'BPJS/ I', 'diagnosa' => 'G3P2A0 H 38 MGG DENGAN TROMBOSITOPENI', 'tindakan' => 'PARTUS SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. YOHANA', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-09-11', 'nama_pasien' => 'NUR NOVIANA', 'no_rm' => '060392', 'status_rawat' => 'BPJS/ I', 'diagnosa' => 'G2P1AO H 36 MGG DENGAN KPD', 'tindakan' => 'PARTUS SPONTAN', 'nama_dokter' => 'DR. JUMADI, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. NINING', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-09-11', 'nama_pasien' => 'SITI MARIA', 'no_rm' => '077050', 'status_rawat' => 'BPJS/ I', 'diagnosa' => 'G1P0AO H 42 MGG DENGAN SEROTINUS+INERSIA UTERI', 'tindakan' => 'PARTUS SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. MEI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-09-12', 'nama_pasien' => 'DELVANI WULANDARI', 'no_rm' => '077085', 'status_rawat' => 'UMUM', 'diagnosa' => 'G2P0A1 H 38MGG DENGAN KPD', 'tindakan' => 'PARTUS SPONTAN', 'nama_dokter' => 'DR STEFANUS SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD YATI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-09-16', 'nama_pasien' => 'RIRIN', 'no_rm' => '077166', 'status_rawat' => 'BPJS/I', 'diagnosa' => 'G3P2A0 H 42 MGG DENGAN SEROTINUS+KPD', 'tindakan' => 'PARTUS SPONTAN', 'nama_dokter' => 'DR STEFANUS SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. NINING', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-09-18', 'nama_pasien' => 'TUT WURI', 'no_rm' => '076909', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G4P2A1 H 40 MGG DENGAN KPD DGN INERSIA UTERI + HAEMOROID GRADE III + HECTING GRADE II', 'tindakan' => 'PARTUS SPONTAN', 'nama_dokter' => 'DR STEFANUS SP. OG', 'asisten_tindakan' => 'BD Grenvy', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-09-20', 'nama_pasien' => 'MIRA SANTIKA', 'no_rm' => '077330', 'status_rawat' => 'BPJS/I', 'diagnosa' => 'G1P0A0 HAMIL 40 MGG DGN KPD 6 JAM', 'tindakan' => 'PARTUS SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. SONNI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-09-27', 'nama_pasien' => 'SULASTRI', 'no_rm' => '077469', 'status_rawat' => 'BPJS/III', 'diagnosa' => 'G2P1A0 HAMIL 36 MGG DGN IUFD', 'tindakan' => 'PARTUS SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'dokter_anak' => 'DR. NOVI', 'asisten_tindakan' => 'BD Grenvy', 'penolong_persalinan' => 'BIDAN'],
            
            // ==================== OKTOBER 2025 ====================
            ['tanggal' => '2025-10-10', 'nama_pasien' => 'NY. WETY', 'no_rm' => '', 'status_rawat' => 'BPJS / I', 'diagnosa' => 'G5P4A0 HAMIL 34 MGG DGN PARTUS PREMATURUS IMMINENS', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'dokter_anak' => 'DR. IRFAN, DR. ETY', 'asisten_tindakan' => 'BD Grenvy, BD. DESSY', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-10-12', 'nama_pasien' => 'NY. NOVI', 'no_rm' => '072112', 'status_rawat' => 'BPJS / I', 'diagnosa' => 'G1P0A0 HAMIL 39-40 MGG DGN INPARTU KALA I FASE AKTIF', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'dokter_anak' => 'DR. RIVANS, SP. A, DR. NOVI', 'asisten_tindakan' => 'BD Grenvy', 'penolong_persalinan' => 'DOKTER'],
            ['tanggal' => '2025-10-28', 'nama_pasien' => 'NY. SITI MASRUROH', 'no_rm' => '078050', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G4P3A0 HAMIL 23-24 MGG DGN IUFD + ENCEPHALOCOTE + LABIOPALATOSCIZIS BILATERAL + INPARTU KALA 2', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'asisten_tindakan' => 'BD Grenvy BD. OKTA', 'penolong_persalinan' => 'BIDAN'],
            
            // ==================== NOVEMBER 2025 ====================
            ['tanggal' => '2025-11-23', 'nama_pasien' => 'NY. MUHAYANIH', 'no_rm' => '078120', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G3P2A0 HAMIL 19-20 MGG DGN BP', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. STEPHANUS, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. MEI', 'penolong_persalinan' => 'BIDAN'],
            ['tanggal' => '2025-11-26', 'nama_pasien' => 'NY. FITRIA', 'no_rm' => '079116', 'status_rawat' => 'BPJS / I', 'diagnosa' => 'G2P1A0 HAMIL 11 MGGN DGN BLIGHTED OVUM', 'tindakan' => 'KURETASE', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'asisten_tindakan' => 'BD Grenvy, BD. YOHANA', 'penolong_persalinan' => 'DOKTER'],
            
            // ==================== DESEMBER 2025 ====================
            ['tanggal' => '2025-12-07', 'nama_pasien' => 'YENI NURAYINI', 'no_rm' => '077402', 'status_rawat' => 'BPJS / III', 'diagnosa' => 'G2P1A0 HAMIL 34 MGG DGN RIW. PEB TERKONTROL', 'tindakan' => 'SPONTAN', 'nama_dokter' => 'DR. YULIANA, SP. OG', 'asisten_tindakan' => 'BD Grenvy', 'penolong_persalinan' => 'BIDAN'],
        ];

        foreach ($dataVK as $data) {
            DataVK::create($data);
        }
    }
}